
########## WILDCARDS
regions:
  NUTS2:
  - ES11
  - ES41
  NUTS3: []
  #- ES111
  #- ES112
  #- ES113
  #- ES114

resources:
- onwind
#- solar

formats:
#- pdf
- png

resolutions:
#- HR
- LR

cutouts:
#- newa
- era5
#- ibera5

years:
#- 2013
- 2023




########## PARAMETERS

cutout_params:
  era5_2023:
    path: "/home/aerolinux4/DOCK_01/SANDBOXES/sandbox_Ryzen3975/cutouts/europe-2023-sarah3-era5.nc"
  ibera5_2023:
    path: "/home/aerolinux4/DOCK_01/SANDBOXES/sandbox_Ryzen3975/cutouts/iberia-2023-era5.nc"

CF_params:
  onwind:
    turbine: Vestas_V112_3MW_h100
    correction_factor:  0.93
    cap_per_sqkm: 10
    CF_threshold: 0.3
  solar:
    panel: CSi
    orientation:
      slope: 35
      azimuth: 180.0
    correction_factor: 0.85
    cap_per_sqkm: 50



fig_params:
  sizes:
    LR:
      size: 12
      linewidth: 1.5
      fontsize: 16
    HR:
      size: 36
      linewidth: 4.5
      fontsize: 48
  cutout:
    onwind:
      cmap: viridis
      units: m/s
    solar:
      cmap: YlOrRd
      units: W/m2
  CF:
    onwind:
      cmap: BuPu
  CAPACITY:
    onwind:
      cmap: YlGn
      units: MW
    solar:
      cmap: YlGn
      units: MW
  CF_CAPACITY:
    size: 12
    fontsize: 16
  ISA:
    colors:
      0: "#d73027"
      1: "#fc8d59"
      2: "#fee08b"
      3: "#91bfdb"
      4: "#1a9850"
    labels:
      0: "Maximum"
      1: "Very high"
      2: "High"
      3: "Moderate"
      4: "Low"



