import numpy as np
import pandas as pd

import rasterio
from rasterio.plot import show
from rasterio.warp import calculate_default_transform, reproject, Resampling
from utils import load_gdf_nuts, load_context_boundaries, log_raster_spatial_info, set_geographic_square_extent

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch

from typing import Any
snakemake: Any  # This is to avoid my IDE to complain about snakemake variable not being defined, but it is actually defined when running the script with snakemake



############################## 
# This script reads the ISA raster for a given resource (solar/wind) and NUTS region, and generates a map showing the distribution of ISA classes (0-4) in the region. The script uses the df_ISA generated by get_df_ISA.py to add the percentage of each class in the legend.



############################## Unwrap relevant variables

##### params
fig_params = snakemake.params["fig_params"]
##### input
file_gdf_NUTS = snakemake.input["gdf_NUTS"]
file_gdf_NUTS_ref = snakemake.input["gdf_NUTS_ref"]
file_raster_ISA = snakemake.input["raster_ISA"]
file_df_ISA = snakemake.input["df_ISA"]
##### output
file_map_ISA = snakemake.output["map_ISA"]
##### wildcards
region = snakemake.wildcards["region"]
resource = snakemake.wildcards["resource"]
resolution = snakemake.wildcards["resolution"]
format = snakemake.wildcards["format"]
nuts = snakemake.wildcards["nuts"]



############################## Operations

##### Load raster_ISA and reproject it to EPSG:4326 for plotting.
# The MITECO ISA raster is in a projected CRS (EPSG:25830, metres). All other
# maps in this workflow (CF, cutout, GEBCO) are drawn in geographic lon/lat
# (EPSG:4326). For small NUTS regions the difference is imperceptible, but for
# large domains (e.g. CIMAS) the projected raster looks visibly skewed/rotated
# relative to the lat/lon rectangle. Reproject to EPSG:4326 so the ISA map is
# coherent with the rest. Nearest resampling preserves the categorical classes.
plot_crs = "EPSG:4326"
with rasterio.open(file_raster_ISA) as raster_ISA:
    log_raster_spatial_info(raster_ISA, source_label=file_raster_ISA)

    src_crs = raster_ISA.crs
    src_transform = raster_ISA.transform
    src_nodata = raster_ISA.nodata
    src_band = raster_ISA.read(1)

    dst_transform, dst_width, dst_height = calculate_default_transform(
        src_crs, plot_crs, raster_ISA.width, raster_ISA.height, *raster_ISA.bounds
    )

fill_value = src_nodata if src_nodata is not None else np.nan
dst_band = np.full((dst_height, dst_width), fill_value, dtype="float32")
reproject(
    source=src_band,
    destination=dst_band,
    src_transform=src_transform,
    src_crs=src_crs,
    dst_transform=dst_transform,
    dst_crs=plot_crs,
    src_nodata=src_nodata,
    dst_nodata=fill_value,
    resampling=Resampling.nearest,
)

if src_nodata is not None:
    band_masked = np.ma.masked_equal(dst_band, src_nodata)
else:
    band_masked = np.ma.masked_invalid(dst_band)

raster_crs = plot_crs
transform = dst_transform

##### Load df_ISA
df = pd.read_csv(file_df_ISA, index_col="value")

##### Load local geometry (black outline) and context boundaries (grey),
##### both in the same (geographic) CRS used for plotting.
_, gdf_NUTS_local = load_gdf_nuts(file_gdf_NUTS, region)
gdf_NUTS_local = gdf_NUTS_local.to_crs(raster_crs)
gdf_context = load_context_boundaries(file_gdf_NUTS_ref, nuts).to_crs(raster_crs)



##### Prepare for plotting

# Get colors and labels from config
colors_contraste = [fig_params["ISA"]["colors"][cls] for cls in range(5)]
cmap = ListedColormap(colors_contraste)

# Define legend:
labels = {
    cls: f"{cls}: {fig_params['ISA']['labels'][cls]} ({df.loc[str(cls), 'porc']:.2f}%)"
    for cls in range(5)
}

legend_elements = [
    Patch(facecolor=colors_contraste[cls], edgecolor='black', label=labels[cls])
    for cls in labels.keys()
]



############################## Create outputs

size = fig_params["sizes"][resolution]["size"]
linewidth = fig_params["sizes"][resolution]["linewidth"]
fontsize = fig_params["sizes"][resolution]["fontsize"]
dpi = fig_params["sizes"][resolution]["dpi"]

##### Make plot
fig, ax = plt.subplots(figsize=(size, size))

# It seems that current version of the show function normalises the band values between 0 and 1? I need to set vmin=0 and vmax=1 to get proper colour assesment
show(band_masked,
    transform=transform,
    cmap=cmap,
    vmin=0,
    vmax=1,
    ax=ax
)

# Context regions (thin grey): same-level NUTS, or NUTS3 for a CIMAS domain.
gdf_context.plot(ax=ax, color="none", edgecolor='grey', linewidth=linewidth)

# Region/domain being plotted (thick black).
gdf_NUTS_local.plot(ax=ax, color="none", edgecolor='black', linewidth=linewidth*2)

# Add legend
ax.legend(
    handles=legend_elements, 
    title='ISA code',
    loc='upper right', 
    fontsize=fontsize,
    title_fontsize=fontsize,
    frameon=True, 
    bbox_to_anchor=(1.4, 1),  # legend out of the plot    
)

# Set square, distance-proportionate limits with the cos(lat) correction, the
# same convention used for the CF/cutout/GEBCO maps, so the ISA map is coherent.
# show() forces aspect='equal'; reset to 'auto' so the km-corrected limits drive
# the appearance, as in the other maps.
ax.set_aspect("auto")
set_geographic_square_extent(ax, gdf_NUTS_local)

ax.set_xticks([])
ax.set_yticks([])



##### Save figure
fig.savefig(file_map_ISA,
            bbox_inches="tight",
            pad_inches=0.2,
            dpi=dpi)  

plt.close(fig)