import numpy as np
import pandas as pd

import rasterio
from rasterio.plot import show
from utils import load_gdf_nuts, log_raster_spatial_info

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch

from typing import Any
snakemake: Any  # This is to avoid my IDE to complain about snakemake variable not being defined, but it is actually defined when running the script with snakemake



############################## 
# This script reads the ISA raster for a given resource (solar/wind) and NUTS region, and generates a map showing the distribution of ISA classes (0-4) in the region. The script uses the df_ISA generated by get_df_ISA.py to add the percentage of each class in the legend.



############################## Unwrap relevant variables

##### params
fig_params = snakemake.params["fig_params"]
##### input
file_gdf_NUTS = snakemake.input["gdf_NUTS"]
file_raster_ISA = snakemake.input["raster_ISA"]
file_df_ISA = snakemake.input["df_ISA"]
##### output
file_map_ISA = snakemake.output["map_ISA"]
##### wildcards
region = snakemake.wildcards["region"]
resource = snakemake.wildcards["resource"]
resolution = snakemake.wildcards["resolution"]
format = snakemake.wildcards["format"]



############################## Operations

##### Load raster_ISA and read required attributes
with rasterio.open(file_raster_ISA) as raster_ISA:
    log_raster_spatial_info(raster_ISA, source_label=file_raster_ISA)

    raster_crs = raster_ISA.crs
    transform = raster_ISA.transform
    band = raster_ISA.read(1)
    band_masked = raster_ISA.read(1, masked=True) # This is for plotting, to avoid showing nodata values in white.

##### Load df_ISA
df = pd.read_csv(file_df_ISA, index_col="value")

##### Load gdf_NUTS and change crs to that of the ISA raster 
gdf_NUTS, gdf_NUTS_local = load_gdf_nuts(file_gdf_NUTS, region)
gdf_NUTS = gdf_NUTS.to_crs(raster_crs)
gdf_NUTS_local = gdf_NUTS_local.to_crs(raster_crs)



##### Prepare for plotting

# Get colors and labels from config
colors_contraste = [fig_params["ISA"]["colors"][cls] for cls in range(5)]
cmap = ListedColormap(colors_contraste)

# Define legend:
labels = {
    cls: f"{cls}: {fig_params['ISA']['labels'][cls]} ({df.loc[str(cls), 'porc']:.2f}%)"
    for cls in range(5)
}

legend_elements = [
    Patch(facecolor=colors_contraste[cls], edgecolor='black', label=labels[cls])
    for cls in labels.keys()
]



############################## Create outputs

size = fig_params["sizes"][resolution]["size"]
linewidth = fig_params["sizes"][resolution]["linewidth"]
fontsize = fig_params["sizes"][resolution]["fontsize"]

##### Make plot
fig, ax = plt.subplots(figsize=(size, size))

# It seems that current version of the show function normalises the band values between 0 and 1? I need to set vmin=0 and vmax=1 to get proper colour assesment
show(band_masked,
    transform=transform,
    cmap=cmap,
    vmin=0,
    vmax=1,
    ax=ax
)

# Add gdf for regions with the same NUTS code with thin grey lines
gdf_NUTS[gdf_NUTS['LEVL_CODE'] == gdf_NUTS_local['LEVL_CODE'].iloc[0]].plot(ax=ax, color="none", edgecolor='grey', linewidth=linewidth)

# Add gdf_local with double linewidth
gdf_NUTS_local.plot(ax=ax, color="none", edgecolor='black', linewidth=linewidth*2)

# Add legend
ax.legend(
    handles=legend_elements, 
    title='ISA code',
    loc='upper right', 
    fontsize=fontsize,
    title_fontsize=fontsize,
    frameon=True, 
    bbox_to_anchor=(1.4, 1),  # legend out of the plot    
)

# Set limits. Note that we cannot use the same logic as plot_dataarray_on_map because the raster has a CRS different from 3035
xmin, ymin, xmax, ymax = gdf_NUTS_local.total_bounds
center_x = (xmax + xmin) / 2
center_y = (ymax + ymin) / 2
delta_x = xmax - xmin
delta_y = ymax - ymin

pad = 0.02

ax.set_xlim(xmin - pad*delta_x, xmax + pad*delta_x)
ax.set_ylim(ymin - pad*delta_y, ymax + pad*delta_y)

ax.set_xticks([])
ax.set_yticks([])



##### Save figure
fig.savefig(file_map_ISA,
            bbox_inches="tight",
            pad_inches=0.2)  

plt.close(fig)