#################### get_tex_summary
#
# This rule generates a LaTeX summary file for one region.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - nuts       [NUTS0, NUTS2, NUTS3]
#   - region     [ES, ES11, ...]
#   - resource   [onwind, solar]
#   - year       [2013, ...]
#   - resolution [HR, LR]


def get_tex_fig_ext(wc):
    return "pdf" if wc.resolution == "HR" else "png"


rule get_tex_summary:
    wildcard_constraints:
        nuts="NUTS0|NUTS2|NUTS3|CIMAS",
        resolution="HR|LR",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_summary",
            f"benchmarks/get_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/get_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_summary",
            f"benchmarks/get_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/get_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_summary/{cutout}/{nuts}/{resolution}/get_tex_summary_{resource}_{region}_{year}.tsv"
    message:
        "... [get_tex_summary] Generating LaTeX summary for cutout: {wildcards.cutout}, nuts: {wildcards.nuts}, year: {wildcards.year}, resource: {wildcards.resource}, region: {wildcards.region}, resolution: {wildcards.resolution}."
    params:
        fig_ext=get_tex_fig_ext,
    input:
        template=lambda w: (
            "LaTex/template_summary_onwind.tex"
            if w.resource == "onwind"
            else f"LaTex/template_summary_{w.resource}.tex"
        ),
        nuts_geojson=gdf_nuts_input,
        df_summary="results/dfs/summary/{cutout}/{nuts}/df_summary_{resource}_{year}.csv",
        map_ISA=lambda w: f"results/maps/ISA/{w.nuts}/{w.resolution}/ISA_{w.resource}_{w.region}_{w.resolution}.{get_tex_fig_ext(w)}",
        map_CF=lambda w: f"results/maps/CF/{w.cutout}/{w.nuts}/CF_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
        map_CAPACITY=lambda w: f"results/maps/CAPACITY/{w.cutout}/{w.nuts}/CAPACITY_CFth_ISA4_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
        plot_CF_CAPACITY=lambda w: f"results/figs/CF_CAPACITY/{w.cutout}/{w.nuts}/CF_CAPACITY_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
    output:
        tex_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.tex"
    shell:
        (
            "python scripts/get_tex_summary.py "
            "--region {wildcards.region} "
            "--cutout {wildcards.cutout} "
            "--year {wildcards.year} "
            "--resource {wildcards.resource} "
            "--nuts {wildcards.nuts} "
            "--resolution {wildcards.resolution} "
            "--fig-ext {params.fig_ext} "
            "--nuts-geojson {input.nuts_geojson} "
            "--template {input.template}"
        )


#################### compile_tex_summary
#
# This rule compiles the LaTeX summary (.tex) generated by get_tex_summary
# into a final PDF file.
#
# Notes:
#   - Runs pdflatex twice to resolve cross-references consistently.
#   - pdflatex binary selection is explicit:
#       1) Prefer /usr/bin/pdflatex (system TeX Live).
#       2) If /usr/bin/pdflatex does not exist, fallback to `command -v pdflatex`.
#     This avoids failures observed with some environment-provided TeX binaries.
#   - On failure, prints the tail of the .log file for quick diagnostics.
#   - Removes temporary .aux and .log files after successful compilation.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - nuts       [NUTS0, NUTS2, NUTS3]
#   - region     [ES, ES11, ...]
#   - resource   [onwind, solar]
#   - year       [2013, ...]
#   - resolution [HR, LR]

rule compile_tex_summary:
    wildcard_constraints:
        nuts="NUTS0|NUTS2|NUTS3|CIMAS",
        resolution="HR|LR",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "compile_tex_summary",
            f"benchmarks/compile_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/compile_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "compile_tex_summary",
            f"benchmarks/compile_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/compile_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/compile_tex_summary/{cutout}/{nuts}/{resolution}/compile_tex_summary_{resource}_{region}_{year}.tsv"
    message:
        "... [compile_tex_summary] Compiling PDF summary for cutout: {wildcards.cutout}, nuts: {wildcards.nuts}, year: {wildcards.year}, resource: {wildcards.resource}, region: {wildcards.region}, resolution: {wildcards.resolution}."
    input:
        tex_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.tex"
    output:
        pdf_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.pdf"
    shell:
        (
            "set -euo pipefail; "
            "TEX_DIR=$(dirname {input.tex_summary}); "
            "TEX_BASE=summary_{wildcards.region}_{wildcards.resolution}; "
            "PDFLATEX_BIN=/usr/bin/pdflatex; "
            "if [ ! -x \"$PDFLATEX_BIN\" ]; then PDFLATEX_BIN=$(command -v pdflatex); fi; "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_summary} >/dev/null || "
            "(echo '[compile_tex_summary] First pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_summary} >/dev/null || "
            "(echo '[compile_tex_summary] Second pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "rm -f \"$TEX_DIR/$TEX_BASE.aux\" \"$TEX_DIR/$TEX_BASE.log\" \"$TEX_DIR/$TEX_BASE.out\""
        )


#################### get_tex_NUTS
#
# This rule generates a LaTeX file for the NUTS-level overview.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule get_tex_NUTS:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_NUTS",
            f"benchmarks/get_tex_NUTS/{w.cutout}/{w.resource}/{w.nuts}/get_tex_NUTS_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_NUTS",
            f"benchmarks/get_tex_NUTS/{w.cutout}/{w.resource}/{w.nuts}/get_tex_NUTS_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_NUTS/{cutout}/{resource}/{nuts}/get_tex_NUTS_{nuts}_{year}.tsv"
    message:
        "... [get_tex_NUTS] Generating LaTeX file for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    params:
        cutout_label=lambda w: {
            "newa": "New European Wind Atlas (NEWA)",
            "era5": "ERA5",
        }.get(w.cutout, w.cutout),
    input:
        template=lambda w: (
            "LaTex/template_NUTS_onwind.tex"
            if w.resource == "onwind"
            else f"LaTex/template_NUTS_{w.resource}.tex"
        ),
        map_NUTS="results/maps/NUTS/{nuts}/NUTS_{nuts}.pdf",
        config="config/config.yaml"
    output:
        tex_nuts="results/LaTex/{cutout}/{year}/{resource}/{nuts}/NUTS_{nuts}.tex"
    shell:
        (
            "python scripts/get_tex_NUTS.py "
            "--nuts {wildcards.nuts} "
            "--cutout {wildcards.cutout} "
            "--cutout-label \"{params.cutout_label}\" "
            "--year {wildcards.year} "
            "--resource {wildcards.resource}"
        )


#################### compile_tex_NUTS
#
# This rule compiles the LaTeX file generated by get_tex_NUTS into a PDF.
#
# Notes:
#   - Runs pdflatex twice to resolve cross-references consistently.
#   - pdflatex binary selection is explicit:
#       1) Prefer /usr/bin/pdflatex (system TeX Live).
#       2) If /usr/bin/pdflatex does not exist, fallback to `command -v pdflatex`.
#   - On failure, prints the tail of the .log file for quick diagnostics.
#   - Removes temporary .aux and .log files after successful compilation.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule compile_tex_NUTS:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "compile_tex_NUTS",
            f"benchmarks/compile_tex_NUTS/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_NUTS_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "compile_tex_NUTS",
            f"benchmarks/compile_tex_NUTS/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_NUTS_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/compile_tex_NUTS/{cutout}/{resource}/{nuts}/compile_tex_NUTS_{nuts}_{year}.tsv"
    message:
        "... [compile_tex_NUTS] Compiling PDF for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        tex_nuts="results/LaTex/{cutout}/{year}/{resource}/{nuts}/NUTS_{nuts}.tex"
    output:
        pdf_nuts="results/LaTex/{cutout}/{year}/{resource}/{nuts}/NUTS_{nuts}.pdf"
    shell:
        (
            "set -euo pipefail; "
            "TEX_DIR=$(dirname {input.tex_nuts}); "
            "TEX_BASE=NUTS_{wildcards.nuts}; "
            "PDFLATEX_BIN=/usr/bin/pdflatex; "
            "if [ ! -x \"$PDFLATEX_BIN\" ]; then PDFLATEX_BIN=$(command -v pdflatex); fi; "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_nuts} >/dev/null || "
            "(echo '[compile_tex_NUTS] First pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_nuts} >/dev/null || "
            "(echo '[compile_tex_NUTS] Second pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "rm -f \"$TEX_DIR/$TEX_BASE.aux\" \"$TEX_DIR/$TEX_BASE.log\" \"$TEX_DIR/$TEX_BASE.out\""
        )


#################### get_tex_cover
#
# This rule generates a LaTeX cover file for one cutout/year/resource/NUTS level.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule get_tex_cover:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_cover",
            f"benchmarks/get_tex_cover/{w.cutout}/{w.resource}/{w.nuts}/get_tex_cover_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_cover",
            f"benchmarks/get_tex_cover/{w.cutout}/{w.resource}/{w.nuts}/get_tex_cover_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_cover/{cutout}/{resource}/{nuts}/get_tex_cover_{nuts}_{year}.tsv"
    message:
        "... [get_tex_cover] Generating LaTeX cover for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        template=lambda w: (
            "LaTex/template_cover_onwind.tex"
            if w.resource == "onwind"
            else f"LaTex/template_cover_{w.resource}.tex"
        )
    output:
        tex_cover="results/LaTex/{cutout}/{year}/{resource}/{nuts}/cover_{nuts}.tex"
    shell:
        (
            "python scripts/get_tex_cover.py "
            "--nuts {wildcards.nuts} "
            "--cutout {wildcards.cutout} "
            "--year {wildcards.year} "
            "--resource {wildcards.resource} "
            "--template {input.template}"
        )


#################### compile_tex_cover
#
# This rule compiles the LaTeX cover (.tex) generated by get_tex_cover
# into a final PDF file.
#
# Notes:
#   - Runs pdflatex twice to resolve cross-references consistently.
#   - pdflatex binary selection is explicit:
#       1) Prefer /usr/bin/pdflatex (system TeX Live).
#       2) If /usr/bin/pdflatex does not exist, fallback to `command -v pdflatex`.
#   - On failure, prints the tail of the .log file for quick diagnostics.
#   - Removes temporary .aux and .log files after successful compilation.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule compile_tex_cover:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "compile_tex_cover",
            f"benchmarks/compile_tex_cover/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_cover_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "compile_tex_cover",
            f"benchmarks/compile_tex_cover/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_cover_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/compile_tex_cover/{cutout}/{resource}/{nuts}/compile_tex_cover_{nuts}_{year}.tsv"
    message:
        "... [compile_tex_cover] Compiling PDF cover for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        tex_cover="results/LaTex/{cutout}/{year}/{resource}/{nuts}/cover_{nuts}.tex"
    output:
        pdf_cover="results/LaTex/{cutout}/{year}/{resource}/{nuts}/cover_{nuts}.pdf"
    shell:
        (
            "set -euo pipefail; "
            "TEX_DIR=$(dirname {input.tex_cover}); "
            "TEX_BASE=cover_{wildcards.nuts}; "
            "PDFLATEX_BIN=/usr/bin/pdflatex; "
            "if [ ! -x \"$PDFLATEX_BIN\" ]; then PDFLATEX_BIN=$(command -v pdflatex); fi; "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_cover} >/dev/null || "
            "(echo '[compile_tex_cover] First pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_cover} >/dev/null || "
            "(echo '[compile_tex_cover] Second pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "rm -f \"$TEX_DIR/$TEX_BASE.aux\" \"$TEX_DIR/$TEX_BASE.log\" \"$TEX_DIR/$TEX_BASE.out\""
        )


#################### get_tex_Venn
#
# This rule generates a LaTeX file with the Venn-diagrams figure for a given
# NUTS level.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule get_tex_Venn:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_Venn",
            f"benchmarks/get_tex_Venn/{w.cutout}/{w.resource}/{w.nuts}/get_tex_Venn_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_Venn",
            f"benchmarks/get_tex_Venn/{w.cutout}/{w.resource}/{w.nuts}/get_tex_Venn_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_Venn/{cutout}/{resource}/{nuts}/get_tex_Venn_{nuts}_{year}.tsv"
    message:
        "... [get_tex_Venn] Generating Venn LaTeX file for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        template=lambda w: (
            "LaTex/template_Venn_onwind.tex"
            if w.resource == "onwind"
            else f"LaTex/template_Venn_{w.resource}.tex"
        ),
        venn_fig="results/figs/venn_all/{cutout}/{nuts}/venn_all_{resource}_{year}.pdf"
    output:
        tex_venn="results/LaTex/{cutout}/{year}/{resource}/{nuts}/Venn_{nuts}.tex"
    shell:
        (
            "python scripts/get_tex_Venn.py "
            "--nuts {wildcards.nuts} "
            "--cutout {wildcards.cutout} "
            "--year {wildcards.year} "
            "--resource {wildcards.resource} "
            "--template {input.template}"
        )


#################### compile_tex_Venn
#
# This rule compiles the LaTeX file generated by get_tex_Venn into a PDF.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule compile_tex_Venn:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "compile_tex_Venn",
            f"benchmarks/compile_tex_Venn/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_Venn_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "compile_tex_Venn",
            f"benchmarks/compile_tex_Venn/{w.cutout}/{w.resource}/{w.nuts}/compile_tex_Venn_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/compile_tex_Venn/{cutout}/{resource}/{nuts}/compile_tex_Venn_{nuts}_{year}.tsv"
    message:
        "... [compile_tex_Venn] Compiling Venn PDF for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        tex_venn="results/LaTex/{cutout}/{year}/{resource}/{nuts}/Venn_{nuts}.tex"
    output:
        pdf_venn="results/LaTex/{cutout}/{year}/{resource}/{nuts}/Venn_{nuts}.pdf"
    shell:
        (
            "set -euo pipefail; "
            "TEX_DIR=$(dirname {input.tex_venn}); "
            "TEX_BASE=Venn_{wildcards.nuts}; "
            "PDFLATEX_BIN=/usr/bin/pdflatex; "
            "if [ ! -x \"$PDFLATEX_BIN\" ]; then PDFLATEX_BIN=$(command -v pdflatex); fi; "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_venn} >/dev/null || "
            "(echo '[compile_tex_Venn] First pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_venn} >/dev/null || "
            "(echo '[compile_tex_Venn] Second pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "rm -f \"$TEX_DIR/$TEX_BASE.aux\" \"$TEX_DIR/$TEX_BASE.log\" \"$TEX_DIR/$TEX_BASE.out\""
        )


#################### get_tex_table_ISA
#
# This rule generates a LaTeX table with ISA surface distribution by region
# for one NUTS level and resource.
#
# Wildcards:
#   - nuts       [NUTS2, NUTS3]
#   - resource   [onwind, solar]

rule get_tex_table_ISA:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_table_ISA",
            f"benchmarks/get_tex_table_ISA/{w.resource}/{w.nuts}/get_tex_table_ISA_{w.resource}_{w.nuts}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_table_ISA",
            f"benchmarks/get_tex_table_ISA/{w.resource}/{w.nuts}/get_tex_table_ISA_{w.resource}_{w.nuts}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_table_ISA/{resource}/{nuts}/get_tex_table_ISA_{resource}_{nuts}.tsv"
    message:
        "... [get_tex_table_ISA] Generating ISA table LaTeX for resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        dfs=lambda w: [
            f"results/dfs/ISA/{w.nuts}/df_ISA_{w.resource}_{region}.csv"
            for nuts, region in REGION_NUTS_PAIRS
            if nuts == w.nuts
        ],
        nuts_geojson="data/NUTS/NUTS_RG_01M_2021_4326_ES.geojson",
    output:
        tex_table_isa="results/LaTex/tables/ISA/{nuts}/table_ISA_{resource}_{nuts}.tex"
    shell:
        (
            "python scripts/get_tex_table_ISA.py "
            "--nuts {wildcards.nuts} "
            "--resource {wildcards.resource} "
            "--output {output.tex_table_isa}"
        )


#################### get_tex_table_summary
#
# This rule generates a LaTeX summary table for all configured regions of one
# NUTS level from the regional summary dataframe.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule get_tex_table_summary:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_table_summary",
            f"benchmarks/get_tex_table_summary/{w.cutout}/{w.resource}/{w.nuts}/get_tex_table_summary_{w.resource}_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_table_summary",
            f"benchmarks/get_tex_table_summary/{w.cutout}/{w.resource}/{w.nuts}/get_tex_table_summary_{w.resource}_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_table_summary/{cutout}/{resource}/{nuts}/get_tex_table_summary_{resource}_{nuts}_{year}.tsv"
    message:
        "... [get_tex_table_summary] Generating summary table LaTeX for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        df_summary="results/dfs/summary/{cutout}/{nuts}/df_summary_{resource}_{year}.csv",
        nuts_geojson="data/NUTS/NUTS_RG_01M_2021_4326_ES.geojson",
    output:
        tex_table_summary="results/LaTex/tables/summary/{cutout}/{year}/{resource}/{nuts}/table_summary_{resource}_{nuts}.tex"
    shell:
        (
            "python scripts/get_tex_table_summary.py "
            "--cutout {wildcards.cutout} "
            "--year {wildcards.year} "
            "--nuts {wildcards.nuts} "
            "--resource {wildcards.resource} "
            "--output {output.tex_table_summary}"
        )


#################### get_tex_DECK
#
# This rule builds a DECK PDF by concatenating:
#   1) cover_{nuts}.pdf
#   2) NUTS_{nuts}.pdf
#   3) all summary PDFs for that NUTS level in alphabetical order
#   4) Venn_{nuts}.pdf
#
# Wildcards:
#   - cutout     [era5, ...]
#   - year       [2013, ...]
#   - resource   [onwind, solar]
#   - nuts       [NUTS2, NUTS3]

rule get_tex_DECK:
    wildcard_constraints:
        nuts="NUTS2|NUTS3",
        resource="onwind|solar",
    threads:
        lambda w: get_rule_threads(
            "get_tex_DECK",
            f"benchmarks/get_tex_DECK/{w.cutout}/{w.resource}/{w.nuts}/get_tex_DECK_{w.nuts}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_DECK",
            f"benchmarks/get_tex_DECK/{w.cutout}/{w.resource}/{w.nuts}/get_tex_DECK_{w.nuts}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_DECK/{cutout}/{resource}/{nuts}/get_tex_DECK_{nuts}_{year}.tsv"
    message:
        "... [get_tex_DECK] Building DECK PDF for cutout: {wildcards.cutout}, year: {wildcards.year}, resource: {wildcards.resource}, NUTS level: {wildcards.nuts}."
    input:
        cover_pdf="results/LaTex/{cutout}/{year}/{resource}/{nuts}/cover_{nuts}.pdf",
        nuts_pdf="results/LaTex/{cutout}/{year}/{resource}/{nuts}/NUTS_{nuts}.pdf",
        summary_pdfs=lambda w: [
            f"results/LaTex/{w.cutout}/{w.year}/{w.resource}/{w.nuts}/summary_{region}_{resolution}.pdf"
            for region in sorted({r for n, r in REGION_NUTS_PAIRS if n == w.nuts})
            for resolution in sorted(RESOLUTIONS)
        ],
        venn_pdf="results/LaTex/{cutout}/{year}/{resource}/{nuts}/Venn_{nuts}.pdf",
    output:
        deck_pdf="results/LaTex/{cutout}/{year}/{resource}/{nuts}/DECK_{nuts}.pdf"
    shell:
        (
            "python scripts/get_tex_DECK.py "
            "--output {output.deck_pdf} "
            "{input.cover_pdf} "
            "{input.nuts_pdf} "
            "{input.summary_pdfs} "
            "{input.venn_pdf}"
        )
