#################### get_tex_summary
#
# This rule generates a LaTeX summary file for one region.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - nuts       [NUTS0, NUTS2, NUTS3]
#   - region     [ES, ES11, ...]
#   - resource   [onwind, solar]
#   - year       [2013, ...]
#   - resolution [HR, LR]


def get_tex_fig_ext(wc):
    return "pdf" if wc.resolution == "HR" else "png"


rule get_tex_summary:
    wildcard_constraints:
        nuts="NUTS0|NUTS2|NUTS3",
        resolution="HR|LR",
    threads:
        lambda w: get_rule_threads(
            "get_tex_summary",
            f"benchmarks/get_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/get_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "get_tex_summary",
            f"benchmarks/get_tex_summary/{w.cutout}/{w.nuts}/{w.resolution}/get_tex_summary_{w.resource}_{w.region}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/get_tex_summary/{cutout}/{nuts}/{resolution}/get_tex_summary_{resource}_{region}_{year}.tsv"
    message:
        "... [get_tex_summary] Generating LaTeX summary for cutout: {wildcards.cutout}, nuts: {wildcards.nuts}, year: {wildcards.year}, resource: {wildcards.resource}, region: {wildcards.region}, resolution: {wildcards.resolution}."
    params:
        fig_ext=get_tex_fig_ext,
    input:
        template="LaTex/template.tex",
        nuts_geojson="data/NUTS/NUTS_RG_01M_2021_4326_ES.geojson",
        df_summary="results/dfs/summary/{cutout}/{nuts}/df_summary_{resource}_{year}.csv",
        map_ISA=lambda w: f"results/maps/ISA/{w.nuts}/{w.resolution}/ISA_{w.resource}_{w.region}_{w.resolution}.{get_tex_fig_ext(w)}",
        map_CF=lambda w: f"results/maps/CF/{w.cutout}/{w.nuts}/CF_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
        map_CAPACITY=lambda w: f"results/maps/CAPACITY/{w.cutout}/{w.nuts}/CAPACITY_CFth_ISA4_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
        plot_CF_CAPACITY=lambda w: f"results/figs/CF_CAPACITY/{w.cutout}/{w.nuts}/CF_CAPACITY_{w.resource}_{w.region}_{w.year}.{get_tex_fig_ext(w)}",
    output:
        tex_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.tex"
    shell:
        (
            "python scripts/get_tex_summary.py "
            "--region {wildcards.region} "
            "--cutout {wildcards.cutout} "
            "--year {wildcards.year} "
            "--resource {wildcards.resource} "
            "--nuts {wildcards.nuts} "
            "--resolution {wildcards.resolution} "
            "--fig-ext {params.fig_ext}"
        )


#################### compile_tex_single
#
# This rule compiles the LaTeX summary (.tex) generated by get_tex_summary
# into a final PDF file.
#
# Notes:
#   - Runs pdflatex twice to resolve cross-references consistently.
#   - pdflatex binary selection is explicit:
#       1) Prefer /usr/bin/pdflatex (system TeX Live).
#       2) If /usr/bin/pdflatex does not exist, fallback to `command -v pdflatex`.
#     This avoids failures observed with some environment-provided TeX binaries.
#   - On failure, prints the tail of the .log file for quick diagnostics.
#   - Removes temporary .aux and .log files after successful compilation.
#
# Wildcards:
#   - cutout     [era5, ...]
#   - nuts       [NUTS0, NUTS2, NUTS3]
#   - region     [ES, ES11, ...]
#   - resource   [onwind, solar]
#   - year       [2013, ...]
#   - resolution [HR, LR]

rule compile_tex_single:
    wildcard_constraints:
        nuts="NUTS0|NUTS2|NUTS3",
        resolution="HR|LR",
    threads:
        lambda w: get_rule_threads(
            "compile_tex_single",
            f"benchmarks/compile_tex_single/{w.cutout}/{w.nuts}/{w.resolution}/compile_tex_single_{w.resource}_{w.region}_{w.year}.tsv",
        )
    resources:
        mem_mb=lambda w: get_rule_mem_mb(
            "compile_tex_single",
            f"benchmarks/compile_tex_single/{w.cutout}/{w.nuts}/{w.resolution}/compile_tex_single_{w.resource}_{w.region}_{w.year}.tsv",
        )
    benchmark:
        "benchmarks/compile_tex_single/{cutout}/{nuts}/{resolution}/compile_tex_single_{resource}_{region}_{year}.tsv"
    message:
        "... [compile_tex_single] Compiling PDF summary for cutout: {wildcards.cutout}, nuts: {wildcards.nuts}, year: {wildcards.year}, resource: {wildcards.resource}, region: {wildcards.region}, resolution: {wildcards.resolution}."
    input:
        tex_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.tex"
    output:
        pdf_summary="results/LaTex/{cutout}/{year}/{resource}/{nuts}/summary_{region}_{resolution}.pdf"
    shell:
        (
            "set -euo pipefail; "
            "TEX_DIR=$(dirname {input.tex_summary}); "
            "TEX_BASE=summary_{wildcards.region}_{wildcards.resolution}; "
            "PDFLATEX_BIN=/usr/bin/pdflatex; "
            "if [ ! -x \"$PDFLATEX_BIN\" ]; then PDFLATEX_BIN=$(command -v pdflatex); fi; "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_summary} >/dev/null || "
            "(echo '[compile_tex_single] First pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "\"$PDFLATEX_BIN\" -interaction=nonstopmode -halt-on-error -file-line-error -output-directory \"$TEX_DIR\" {input.tex_summary} >/dev/null || "
            "(echo '[compile_tex_single] Second pdflatex pass failed. Showing log tail:'; tail -n 120 \"$TEX_DIR/$TEX_BASE.log\"; exit 1); "
            "rm -f \"$TEX_DIR/$TEX_BASE.aux\" \"$TEX_DIR/$TEX_BASE.log\""
        )
